# Generated by Django 4.0.10 on 2023-12-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20231221_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
