# Generated by Django 4.0.10 on 2023-12-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('place', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('lng', 'lat')},
        ),
    ]
