# Generated by Django 4.0.10 on 2023-12-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_image_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
