# Generated by Django 4.0.10 on 2023-12-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_image'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='image',
            index_together={('place', 'order')},
        ),
    ]
