# Generated by Django 4.0.10 on 2023-12-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_image_index_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
    ]
