# Generated by Django 4.0.10 on 2023-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_image_unique_together'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='image',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Позиция'),
        ),
    ]
